'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var radioStations = [{ title: 'BBC Media', src: 'http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_q' }, { title: 'Florida Jass', src: 'http://us4.internet-radio.com:8266/;stream' }, { title: 'UK Dance', src: 'http://uk7.internet-radio.com:8226/;stream' }, { title: 'France: ABC Lounge', src: 'http://centauri.shoutca.st:8686/stream/1/' }, { title: 'UK: Magic', src: 'https://stream-mz.planetradio.co.uk/magicnational.aac' }, { title: 'Eugene, USA: Wisperings Piano Solo', src: 'http://pianosolo.streamguys.net/live' }, { title: 'USA: Country', src: 'http://50.7.70.58:8708/;/;5348241552822155stream.nsv' }, { title: 'USA: Country Hits', src: 'http://19763.live.streamtheworld.com/977_COUNTRY.mp3' }, { title: 'Zug: Absolute Top 40', src: 'http://strm112.1.fm/top40_mobile_mp3' }, { title: 'Spain: Costa Del Mar - Chillout', src: 'http://stream.cdm-chillout.com:8020/stream-mp3-Chill', siteUrl: 'http://www.costadelmar-radio.com' }, { title: 'USA: Classic Rock Florida', src: 'http://us4.internet-radio.com:8258/;stream', siteUrl: 'http://www.classicrockflorida.com' }, { title: 'Seattle: KEXP 90.3 FM', src: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3', siteUrl: 'http://kexp.org/' }, { title: 'Santa Monica, California: KCRW 89.9 FM', src: 'https://kcrw.streamguys1.com/kcrw_192k_mp3_on_air?listenerid=1a13cb86cbe44b773c014c34bb7bfe43&awparams=companionAds%3Atrue', siteUrl: 'https://www.kcrw.com/' }, { title: 'Portland, Oregon: XRAY.FM KXRY 107.1 FM', src: 'http://listen.xray.fm:8000/stream', siteUrl: 'https://xray.fm/' }, { title: 'Music Lake', src: 'http://50.7.68.251:7168/;stream/1', siteUrl: 'http://musiclake.com/' }, { title: 'Instrumental Radio ', src: 'http://178.32.62.163:8599/;stream/1', siteUrl: 'http://www.instrumentalradio.eu' }, { title: 'Smooth Jazz Florida ', src: 'http://us4.internet-radio.com:8266/;stream', siteUrl: 'http://www.SmoothJazzFlorida.com' }, { title: 'UK: Classic: Davide of MIMIC ', src: 'http://uk3.internet-radio.com:8060/;stream', siteUrl: 'http://meetinginmusic.blogspot.com ' }, { title: 'BBC Radio Wales 103.9 Cardiff', src: 'http://bbcmedia.ic.llnwd.net/stream/bbcmedia_walesmw_mf_p', siteUrl: 'http://www.bbc.co.uk/radiowales' }, { title: 'USA: Bristol: ESPN Radio', src: 'http://edge.espn.cdn.abacast.net/espn-networkmp3-48', siteUrl: 'http://www.espn.com/espnradio/' }];

exports.default = radioStations;
//# sourceMappingURL=radioStations.js.map